#!/bin/bash

cd dynamic-panel-transparency@rockon999.github.io

xgettext -k_ -kN_ -o dynamic-panel-transparency.pot prefs.js/preferences/main.js prefs.js/ui/prefs.ui prefs.js/ui/app-prefs.ui

cd locale

for subdir in */ ; do
    msgmerge -U "$subdir/LC_MESSAGES/dynamic-panel-transparency.po" "../dynamic-panel-transparency.pot"
    msgfmt "$subdir/LC_MESSAGES/dynamic-panel-transparency.po" -o "$subdir/LC_MESSAGES/dynamic-panel-transparency.mo"
done

cd ..
cd ..

