#!/bin/bash

cd dynamic-panel-transparency@rockon999.github.io

xgettext -k_ -kN_ -o ./po/dynamic-panel-transparency.pot src/prefs.ts src/prefs.ui

cd locale

for subdir in */ ; do
    msgmerge -U "$subdir/LC_MESSAGES/dynamic-panel-transparency.po" "../po/dynamic-panel-transparency.pot"
    msgfmt "$subdir/LC_MESSAGES/dynamic-panel-transparency.po" -o "$subdir/LC_MESSAGES/dynamic-panel-transparency.mo"
done

cd ..
cd ..

